import clsx from 'clsx';
import type { Metadata } from 'next';
import { ZCOOL_KuaiLe } from 'next/font/google';

import '@/app/css/globals.css';
import { AppSidebar } from '@/components/app-sidebar';
import { ThemeProvider } from '@/components/theme-provider';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';

const FONT_ZCOOL_KUAILE = ZCOOL_KuaiLe({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  variable: '--font-zcool-kuaile',
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={clsx('scroll-smooth', FONT_ZCOOL_KUAILE.variable)}
      suppressHydrationWarning
    >
      <body
        className={clsx([
          'antialiased',
          'relative min-h-screen pl-[calc(100vw-100%)]',
          'flex flex-col',
          'bg-white text-gray-900',
          'dark:bg-dark dark:text-gray-100',
        ])}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>{children}</SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
